apiVersion: v1
kind: Pod
metadata:
  name: 'enb-test'
spec:
  nodeName: k8s-node3
  hostNetwork: true
  containers:
  - name: enb
    image: test-zy-enb:4.27
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "6144Mi"
        cpu: "3"
      requests:
        memory: "6144Mi"
        cpu: "3"
    securityContext:
      privileged: true
