apiVersion: v1
kind: Pod
metadata:
  name: 'enb-test2'
spec:
  nodeName: k8s-node3
  hostNetwork: true
  containers:
  - name: enb2
    image: test-zy-enb1:4.28
    imagePullPolicy: IfNotPresent
    resources:
      resources:
      limits:
        memory: "18432Mi"
        cpu: "9"
      requests:
        memory: "18432Mi"
        cpu: "9" 
    securityContext:
      privileged: true
