apiVersion: v1
kind: Pod
metadata:
  name: 'ftp-test'
spec:
  nodeName: k8s-node1
  hostNetwork: true
  containers:
  - name: ftp-test
    image: ftp_test:v1.0
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
