apiVersion: v1
kind: Pod
metadata:
  name: 'mme-ims-test'
spec:
  nodeName: k8s-node1
  hostNetwork: true
  containers:
  - name: mme-ims
    image: test-zy-mme:4.27
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
