apiVersion: v1
kind: Pod 
metadata:
  name: 'yolo-test'
spec:
  nodeName: k8s-node1
  hostNetwork: true
  containers:
    - name: yolo
      image: myyolo:v0.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: yolov5-master
        mountPath: "/home/sdr/conda_test/yolo_test/yolov5-master"
      securityContext:
        privileged: true
      command: ["bash"]
      args: ["-c","sh yolotest.sh"]
  volumes:
  - name: yolov5-master
    hostPath :
      path: /home/sdr/conda_test/yolo_test/yolov5-master
